# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Client:
  fields:
    default: name
    form: name
  order_by: 
  relationships: 
  filters: 
  search: name
  application: fusion

